AWSTemplateFormatVersion: '2010-09-09'
Description: 'Job Portal - EC2 with Web Application'

Parameters:
  ProjectName:
    Type: String
    Default: job-portal
  Environment:
    Type: String
    Default: dev
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  EC2SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  InstanceType:
    Type: String
    Default: t3.micro
  S3BucketName:
    Type: String
  DBEndpoint:
    Type: String
  DBName:
    Type: String
    Default: jobportaldb
  DBUsername:
    Type: String
    Default: admin
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject','s3:ListBucket']
                Resource: [!Sub 'arn:aws:s3:::${S3BucketName}',!Sub 'arn:aws:s3:::${S3BucketName}/*']

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref EC2Role]

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-alb'
      Scheme: internet-facing
      SecurityGroups: [!Ref ALBSecurityGroupId]
      Subnets: !Ref PublicSubnetIds

  TG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-tg'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /health

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TG

  LT:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        SecurityGroupIds: [!Ref EC2SecurityGroupId]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y && yum install -y python3 python3-pip
            pip3 install flask boto3 pymysql
            mkdir -p /var/www/app/templates && cd /var/www/app
            cat > app.py << 'APPEOF'
            import os,boto3,pymysql
            from flask import *
            from werkzeug.utils import secure_filename
            from datetime import datetime
            app=Flask(__name__)
            app.secret_key='s3cr3t'
            e=os.environ.get
            H,U,P,D,B,R=e('DB_HOST'),e('DB_USER'),e('DB_PASSWORD'),e('DB_NAME'),e('S3_BUCKET'),e('AWS_REGION','us-east-1')
            s3=boto3.client('s3',region_name=R)
            def db():
             try:return pymysql.connect(host=H,user=U,password=P,database=D,cursorclass=pymysql.cursors.DictCursor)
             except:return None
            def init():
             c=db()
             if c:
              with c.cursor() as x:x.execute("CREATE TABLE IF NOT EXISTS jobs(id INT AUTO_INCREMENT PRIMARY KEY,company VARCHAR(255),role VARCHAR(255),status VARCHAR(50) DEFAULT 'Applied',resume_key VARCHAR(500),applied_date DATE,notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");c.commit()
              c.close()
            @app.route('/')
            def index():
             c=db();jobs=[]
             if c:
              with c.cursor() as x:x.execute("SELECT * FROM jobs ORDER BY created_at DESC");jobs=x.fetchall()
              c.close()
             return render_template('index.html',jobs=jobs)
            @app.route('/add',methods=['GET','POST'])
            def add():
             if request.method=='POST':
              co,ro,st,dt,nt=request.form.get('company',''),request.form.get('role',''),request.form.get('status','Applied'),request.form.get('date',''),request.form.get('notes','')
              rk=None
              if 'resume' in request.files:
               f=request.files['resume']
               if f and f.filename:
                fn=secure_filename(f.filename);rk=f"resumes/{datetime.now().strftime('%Y%m%d%H%M%S')}_{fn}"
                try:s3.upload_fileobj(f,B,rk)
                except:rk=None
              c=db()
              if c:
               with c.cursor() as x:x.execute("INSERT INTO jobs(company,role,status,resume_key,applied_date,notes)VALUES(%s,%s,%s,%s,%s,%s)",(co,ro,st,rk,dt or None,nt));c.commit()
               c.close();flash('Added!','success')
              return redirect('/')
             return render_template('add.html')
            @app.route('/view/<int:id>')
            def view(id):
             c=db();j=None;url=None
             if c:
              with c.cursor() as x:x.execute("SELECT * FROM jobs WHERE id=%s",(id,));j=x.fetchone()
              c.close()
             if j and j.get('resume_key'):
              try:url=s3.generate_presigned_url('get_object',Params={'Bucket':B,'Key':j['resume_key']},ExpiresIn=3600)
              except:pass
             return render_template('view.html',job=j,url=url)
            @app.route('/delete/<int:id>',methods=['POST'])
            def delete(id):
             c=db()
             if c:
              with c.cursor() as x:x.execute("SELECT resume_key FROM jobs WHERE id=%s",(id,));r=x.fetchone();x.execute("DELETE FROM jobs WHERE id=%s",(id,));c.commit()
              c.close()
              if r and r.get('resume_key'):
               try:s3.delete_object(Bucket=B,Key=r['resume_key'])
               except:pass
              flash('Deleted!','success')
             return redirect('/')
            @app.route('/health')
            def health():return{'status':'ok'},200
            if __name__=='__main__':init();app.run(host='0.0.0.0',port=80)
            APPEOF
            cat > templates/index.html << 'HTMLEOF'
            <!DOCTYPE html><html><head><title>Job Portal</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet"><style>body{background:#f3f4f6}.hero{background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff;padding:2rem;border-radius:12px;margin-bottom:2rem}.card{border:none;border-radius:12px;box-shadow:0 4px 6px rgba(0,0,0,.07)}.card-header{background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff}.btn-primary{background:#4f46e5;border-color:#4f46e5}.st{padding:.3rem .8rem;border-radius:20px;font-size:.85rem}.st-applied{background:#dbeafe;color:#1d4ed8}.st-interview{background:#fef3c7;color:#d97706}.st-offer{background:#d1fae5;color:#059669}.st-rejected{background:#fee2e2;color:#dc2626}</style></head><body><nav class="navbar navbar-dark" style="background:linear-gradient(135deg,#4f46e5,#7c3aed)"><div class="container"><a class="navbar-brand" href="/"><i class="bi bi-briefcase-fill me-2"></i>Job Portal</a><div class="navbar-nav flex-row"><a class="nav-link px-2" href="/">Home</a><a class="nav-link px-2" href="/add">Add</a></div></div></nav><div class="container py-4">{% with m=get_flashed_messages(with_categories=true) %}{% if m %}{% for c,msg in m %}<div class="alert alert-success">{{msg}}</div>{% endfor %}{% endif %}{% endwith %}<div class="hero"><div class="d-flex justify-content-between align-items-center flex-wrap"><div><h2><i class="bi bi-briefcase-fill me-2"></i>Job Application Tracker</h2><p class="mb-0">Track applications, upload resumes, stay organized.</p></div><a href="/add" class="btn btn-light"><i class="bi bi-plus-circle me-2"></i>Add Application</a></div></div><div class="card"><div class="card-header"><i class="bi bi-list-ul me-2"></i>My Applications</div><div class="card-body p-0">{% if jobs %}<table class="table table-hover mb-0"><thead><tr><th>Company</th><th>Role</th><th>Status</th><th>Date</th><th>Resume</th><th>Actions</th></tr></thead><tbody>{% for j in jobs %}<tr><td><strong>{{j.company}}</strong></td><td>{{j.role}}</td><td><span class="st st-{{j.status|lower}}">{{j.status}}</span></td><td>{{j.applied_date.strftime('%b %d') if j.applied_date else '-'}}</td><td>{% if j.resume_key %}<i class="bi bi-check text-success"></i>{% else %}-{% endif %}</td><td><a href="/view/{{j.id}}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a> <form action="/delete/{{j.id}}" method="POST" class="d-inline" onsubmit="return confirm('Delete?')"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>{% endfor %}</tbody></table>{% else %}<div class="text-center py-5"><i class="bi bi-inbox" style="font-size:3rem"></i><h5>No Applications</h5><a href="/add" class="btn btn-primary mt-2">Add Your First</a></div>{% endif %}</div></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script></body></html>
            HTMLEOF
            cat > templates/add.html << 'HTMLEOF'
            <!DOCTYPE html><html><head><title>Add - Job Portal</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet"><style>body{background:#f3f4f6}.card{border:none;border-radius:12px;box-shadow:0 4px 6px rgba(0,0,0,.07)}.card-header{background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff}.btn-primary{background:#4f46e5;border-color:#4f46e5}</style></head><body><nav class="navbar navbar-dark" style="background:linear-gradient(135deg,#4f46e5,#7c3aed)"><div class="container"><a class="navbar-brand" href="/"><i class="bi bi-briefcase-fill me-2"></i>Job Portal</a></div></nav><div class="container py-4"><div class="row justify-content-center"><div class="col-md-8"><div class="card"><div class="card-header"><i class="bi bi-plus-circle me-2"></i>Add Application</div><div class="card-body p-4"><form method="POST" enctype="multipart/form-data"><div class="mb-3"><label class="form-label">Company *</label><input type="text" class="form-control" name="company" required></div><div class="mb-3"><label class="form-label">Role *</label><input type="text" class="form-control" name="role" required></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Status</label><select class="form-select" name="status"><option>Applied</option><option>Interview</option><option>Offer</option><option>Rejected</option></select></div><div class="col-md-6 mb-3"><label class="form-label">Date</label><input type="date" class="form-control" name="date"></div></div><div class="mb-3"><label class="form-label">Resume</label><input type="file" class="form-control" name="resume"><small class="text-muted">Stored in AWS S3</small></div><div class="mb-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div><div class="d-flex justify-content-between"><a href="/" class="btn btn-secondary">Cancel</a><button class="btn btn-primary">Submit</button></div></form></div></div></div></div></div></body></html>
            HTMLEOF
            cat > templates/view.html << 'HTMLEOF'
            <!DOCTYPE html><html><head><title>View - Job Portal</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet"><style>body{background:#f3f4f6}.card{border:none;border-radius:12px;box-shadow:0 4px 6px rgba(0,0,0,.07)}.card-header{background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff}.btn-primary{background:#4f46e5}</style></head><body><nav class="navbar navbar-dark" style="background:linear-gradient(135deg,#4f46e5,#7c3aed)"><div class="container"><a class="navbar-brand" href="/"><i class="bi bi-briefcase-fill me-2"></i>Job Portal</a></div></nav><div class="container py-4"><div class="row justify-content-center"><div class="col-md-8"><a href="/" class="btn btn-secondary mb-3">Back</a><div class="card"><div class="card-header">Application Details</div><div class="card-body p-4"><h3>{{job.company}}</h3><h5 class="text-muted">{{job.role}}</h5><hr><p><strong>Status:</strong> {{job.status}}</p><p><strong>Date:</strong> {{job.applied_date.strftime('%B %d, %Y') if job.applied_date else 'Not set'}}</p>{% if job.resume_key and url %}<p><strong>Resume:</strong> <a href="{{url}}" target="_blank" class="btn btn-sm btn-primary">Download</a></p>{% endif %}{% if job.notes %}<p><strong>Notes:</strong> {{job.notes}}</p>{% endif %}<hr><form action="/delete/{{job.id}}" method="POST" onsubmit="return confirm('Delete?')"><button class="btn btn-danger">Delete</button></form></div></div></div></div></div></body></html>
            HTMLEOF
            cat > /etc/systemd/system/app.service << EOF
            [Unit]
            Description=JobPortal
            After=network.target
            [Service]
            Environment="DB_HOST=${DBEndpoint}"
            Environment="DB_USER=${DBUsername}"
            Environment="DB_PASSWORD=${DBPassword}"
            Environment="DB_NAME=${DBName}"
            Environment="S3_BUCKET=${S3BucketName}"
            Environment="AWS_REGION=${AWS::Region}"
            WorkingDirectory=/var/www/app
            ExecStart=/usr/bin/python3 app.py
            Restart=always
            [Install]
            WantedBy=multi-user.target
            EOF
            systemctl daemon-reload && systemctl enable app && systemctl start app

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LT
        Version: !GetAtt LT.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 1
      VPCZoneIdentifier: !Ref PublicSubnetIds
      TargetGroupARNs: [!Ref TG]
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

Outputs:
  URL:
    Value: !Sub 'http://${ALB.DNSName}'
