AWSTemplateFormatVersion: '2010-09-09'
Description: 'Job Portal - EC2 and Application Load Balancer Stack'

# =============================================================================
# Parameters
# =============================================================================
Parameters:
  ProjectName:
    Type: String
    Default: job-portal
    Description: Name of the project

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be deployed

  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of public subnet IDs for ALB

  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of private subnet IDs for EC2

  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID for ALB

  EC2SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID for EC2 instances

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type

  KeyPairName:
    Type: String
    Default: ''
    Description: EC2 Key Pair name for SSH access

  MinCapacity:
    Type: Number
    Default: 1
    Description: Minimum number of EC2 instances

  MaxCapacity:
    Type: Number
    Default: 3
    Description: Maximum number of EC2 instances

  DesiredCapacity:
    Type: Number
    Default: 2
    Description: Desired number of EC2 instances

# =============================================================================
# Conditions
# =============================================================================
Conditions:
  HasKeyPair: !Not [!Equals [!Ref KeyPairName, '']]

# =============================================================================
# Resources
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # IAM Role for EC2
  # ---------------------------------------------------------------------------
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-ec2-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: S3UploadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${ProjectName}-*/*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectName}-${Environment}-ec2-profile'
      Roles:
        - !Ref EC2Role

  # ---------------------------------------------------------------------------
  # Application Load Balancer
  # ---------------------------------------------------------------------------
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-alb'
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Subnets: !Ref PublicSubnetIds
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-alb'

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-tg'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-tg'

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  # ---------------------------------------------------------------------------
  # Launch Template
  # ---------------------------------------------------------------------------
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${ProjectName}-${Environment}-lt'
      LaunchTemplateData:
        ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
        InstanceType: !Ref InstanceType
        KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref 'AWS::NoValue']
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        SecurityGroupIds:
          - !Ref EC2SecurityGroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y python3 python3-pip git
            pip3 install flask boto3 mysql-connector-python
            
            # Create application directory
            mkdir -p /var/www/job-portal
            cd /var/www/job-portal
            
            # Create a simple health check endpoint
            cat > app.py << 'EOF'
            from flask import Flask, jsonify, render_template_string
            import os
            
            app = Flask(__name__)
            
            @app.route('/health')
            def health():
                return jsonify({'status': 'healthy'}), 200
            
            @app.route('/')
            def home():
                return render_template_string('''
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Job Application Portal</title>
                    <style>
                        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
                        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                        h1 { color: #333; }
                        .instance-info { background: #e7f3ff; padding: 15px; border-radius: 5px; margin-top: 20px; }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <h1>Welcome to Job Application Portal</h1>
                        <p>This is a scalable web application deployed on AWS.</p>
                        <div class="instance-info">
                            <strong>Instance ID:</strong> {{ instance_id }}<br>
                            <strong>Availability Zone:</strong> {{ az }}
                        </div>
                    </div>
                </body>
                </html>
                ''', instance_id=os.popen('curl -s http://169.254.169.254/latest/meta-data/instance-id').read(),
                    az=os.popen('curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone').read())
            
            if __name__ == '__main__':
                app.run(host='0.0.0.0', port=80)
            EOF
            
            # Start the application
            python3 app.py &
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${ProjectName}-${Environment}-web-server'

  # ---------------------------------------------------------------------------
  # Auto Scaling Group
  # ---------------------------------------------------------------------------
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub '${ProjectName}-${Environment}-asg'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinCapacity
      MaxSize: !Ref MaxCapacity
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier: !Ref PublicSubnetIds
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-asg-instance'
          PropagateAtLaunch: true

  # ---------------------------------------------------------------------------
  # Scaling Policies
  # ---------------------------------------------------------------------------
  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 70.0

# =============================================================================
# Outputs
# =============================================================================
Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${ProjectName}-${Environment}-alb-dns'

  LoadBalancerArn:
    Description: ARN of the Application Load Balancer
    Value: !Ref ApplicationLoadBalancer

  TargetGroupArn:
    Description: ARN of the Target Group
    Value: !Ref ALBTargetGroup

  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group
    Value: !Ref AutoScalingGroup
