AWSTemplateFormatVersion: '2010-09-09'
Description: 'Job Portal - RDS Database Stack'

# =============================================================================
# Parameters
# =============================================================================
Parameters:
  ProjectName:
    Type: String
    Default: job-portal
    Description: Name of the project

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where RDS will be deployed

  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of private subnet IDs for RDS

  RDSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID for RDS

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
    Description: RDS instance class

  DBName:
    Type: String
    Default: jobportaldb
    Description: Name of the database

  DBUsername:
    Type: String
    Default: admin
    NoEcho: true
    Description: Database master username

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Database master password (minimum 8 characters)

  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 100
    Description: Allocated storage in GB

# =============================================================================
# Resources
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # DB Subnet Group
  # ---------------------------------------------------------------------------
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-${Environment}-db-subnet-group'
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds: !Ref PrivateSubnetIds
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-subnet-group'

  # ---------------------------------------------------------------------------
  # RDS Instance
  # ---------------------------------------------------------------------------
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${Environment}-db'
      DBInstanceClass: !Ref DBInstanceClass
      Engine: mysql
      EngineVersion: '8.0'
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2
      StorageEncrypted: false
      VPCSecurityGroups:
        - !Ref RDSSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 0
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      DeletionProtection: false
      EnablePerformanceInsights: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db'

# =============================================================================
# Outputs
# =============================================================================
Outputs:
  DBEndpoint:
    Description: Endpoint address of the RDS instance
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-endpoint'

  DBPort:
    Description: Port of the RDS instance
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-port'

  DBName:
    Description: Name of the database
    Value: !Ref DBName

  DBInstanceIdentifier:
    Description: Identifier of the RDS instance
    Value: !Ref DBInstance
